# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "GRcwolf"
    groups:
      drupal-packages:
        patterns:
          - "drupal/*"
          - "drush/drush"
      other-packages:
        patterns:
          - "*"
        exclude-patterns:
          - "drupal/*"
          - "drush/drush"
